package studentinternshipapplication;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CompanyInterface extends javax.swing.JFrame {

    static LoginInterface li;
    boolean allowEdit;
    DBOperations db = new DBOperations();
   ArrayList<String[]> applicantList= new ArrayList<>();
    
    public CompanyInterface(LoginInterface li,boolean allowEdit) {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x_size = 1350;
        int y_size=700;
        this.setSize(x_size,y_size);
        CompanyInterface.li = li;
        this.allowEdit = allowEdit;
        allowChange(allowEdit);
        tab2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVIewApplications1 = new javax.swing.JLabel();
        lblVIewApplications = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblApplications = new javax.swing.JTable();
        mainPanel = new javax.swing.JPanel();
        companyPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblComTel = new javax.swing.JLabel();
        txtComName = new javax.swing.JTextField();
        txtComTel = new javax.swing.JTextField();
        txtComAddress = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtComEmail = new javax.swing.JTextField();
        opportunityPanel = new javax.swing.JPanel();
        lblTiltle = new javax.swing.JLabel();
        lblSlots = new javax.swing.JLabel();
        lblSkills = new javax.swing.JLabel();
        txtOpID = new javax.swing.JTextField();
        lblOpID = new javax.swing.JLabel();
        txtSlots = new javax.swing.JTextField();
        txtOpTitle = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSkills = new javax.swing.JTextArea();
        DescriptionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        ButtonPanel = new javax.swing.JPanel();
        lblUpdate = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        lblNew = new javax.swing.JLabel();
        agnetPanel = new javax.swing.JPanel();
        lblAname = new javax.swing.JLabel();
        lblAid = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblAemail = new javax.swing.JLabel();
        lblAtel = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        txtAgentEmail = new javax.swing.JTextField();
        txtAgentName = new javax.swing.JTextField();
        txtAgentID = new javax.swing.JTextField();
        txtAgentMob = new javax.swing.JTextField();
        lblPosition1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblLogout = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        lblVIewApplications1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblVIewApplications1.setForeground(new java.awt.Color(255, 255, 255));
        lblVIewApplications1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVIewApplications1.setText("View Profile");
        lblVIewApplications1.setAutoscrolls(true);
        lblVIewApplications1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblVIewApplications1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVIewApplications1MouseClicked(evt);
            }
        });
        getContentPane().add(lblVIewApplications1);
        lblVIewApplications1.setBounds(110, 40, 170, 40);

        lblVIewApplications.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblVIewApplications.setForeground(new java.awt.Color(255, 255, 255));
        lblVIewApplications.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVIewApplications.setText("View Applications");
        lblVIewApplications.setAutoscrolls(true);
        lblVIewApplications.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblVIewApplications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVIewApplicationsMouseClicked(evt);
            }
        });
        getContentPane().add(lblVIewApplications);
        lblVIewApplications.setBounds(300, 40, 170, 40);

        tab2.setOpaque(false);

        tblApplications.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tblApplications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Department", "Gender", "GPA", "Languages", "Skills", "Mobile No. ", "Email", "Address", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblApplications.setCellSelectionEnabled(true);
        jScrollPane3.setViewportView(tblApplications);

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        getContentPane().add(tab2);
        tab2.setBounds(30, 110, 1270, 570);

        mainPanel.setOpaque(false);

        companyPanel.setBackground(new java.awt.Color(102, 102, 102));
        companyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Company Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        companyPanel.setForeground(new java.awt.Color(255, 255, 255));
        companyPanel.setOpaque(false);

        lblName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name : ");

        lblAddress.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Address : ");

        lblComTel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblComTel.setForeground(new java.awt.Color(255, 255, 255));
        lblComTel.setText("Tel. Number : ");

        txtComName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtComName.setForeground(new java.awt.Color(255, 255, 255));
        txtComName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtComName.setOpaque(false);

        txtComTel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtComTel.setForeground(new java.awt.Color(255, 255, 255));
        txtComTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtComTel.setOpaque(false);

        txtComAddress.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtComAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtComAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtComAddress.setOpaque(false);

        lblemail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblemail.setForeground(new java.awt.Color(255, 255, 255));
        lblemail.setText("E-mail :");

        txtComEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtComEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtComEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtComEmail.setOpaque(false);

        javax.swing.GroupLayout companyPanelLayout = new javax.swing.GroupLayout(companyPanel);
        companyPanel.setLayout(companyPanelLayout);
        companyPanelLayout.setHorizontalGroup(
            companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyPanelLayout.createSequentialGroup()
                        .addComponent(txtComName, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(lblComTel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComTel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(companyPanelLayout.createSequentialGroup()
                        .addComponent(txtComAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        companyPanelLayout.setVerticalGroup(
            companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyPanelLayout.createSequentialGroup()
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComTel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComTel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtComEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        opportunityPanel.setBackground(new java.awt.Color(102, 102, 102));
        opportunityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Opportunity Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        opportunityPanel.setForeground(new java.awt.Color(255, 255, 255));
        opportunityPanel.setOpaque(false);

        lblTiltle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblTiltle.setForeground(new java.awt.Color(255, 255, 255));
        lblTiltle.setText("Opportunity Title :");

        lblSlots.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblSlots.setForeground(new java.awt.Color(255, 255, 255));
        lblSlots.setText("Available Slots :");

        lblSkills.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblSkills.setForeground(new java.awt.Color(255, 255, 255));
        lblSkills.setText("Required Skills :");

        txtOpID.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtOpID.setForeground(new java.awt.Color(255, 255, 255));
        txtOpID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtOpID.setOpaque(false);

        lblOpID.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblOpID.setForeground(new java.awt.Color(255, 255, 255));
        lblOpID.setText("Opportunity ID : ");

        txtSlots.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtSlots.setForeground(new java.awt.Color(255, 255, 255));
        txtSlots.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtSlots.setOpaque(false);

        txtOpTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtOpTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtOpTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtOpTitle.setOpaque(false);

        jScrollPane2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        txtSkills.setColumns(20);
        txtSkills.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtSkills.setRows(5);
        txtSkills.setOpaque(false);
        jScrollPane2.setViewportView(txtSkills);

        javax.swing.GroupLayout opportunityPanelLayout = new javax.swing.GroupLayout(opportunityPanel);
        opportunityPanel.setLayout(opportunityPanelLayout);
        opportunityPanelLayout.setHorizontalGroup(
            opportunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opportunityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opportunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opportunityPanelLayout.createSequentialGroup()
                        .addComponent(lblTiltle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOpTitle))
                    .addGroup(opportunityPanelLayout.createSequentialGroup()
                        .addComponent(lblSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(opportunityPanelLayout.createSequentialGroup()
                        .addComponent(lblOpID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOpID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSlots, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSlots, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        opportunityPanelLayout.setVerticalGroup(
            opportunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opportunityPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(opportunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiltle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opportunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOpID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSlots, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlots, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(opportunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opportunityPanelLayout.createSequentialGroup()
                        .addComponent(lblSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap())
        );

        DescriptionPanel.setBackground(new java.awt.Color(102, 102, 102));
        DescriptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        DescriptionPanel.setOpaque(false);

        jScrollPane1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtDescription.setRows(5);
        txtDescription.setOpaque(false);
        jScrollPane1.setViewportView(txtDescription);

        javax.swing.GroupLayout DescriptionPanelLayout = new javax.swing.GroupLayout(DescriptionPanel);
        DescriptionPanel.setLayout(DescriptionPanelLayout);
        DescriptionPanelLayout.setHorizontalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        DescriptionPanelLayout.setVerticalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(10, 10, 10))
        );

        ButtonPanel.setBackground(new java.awt.Color(102, 102, 102));
        ButtonPanel.setOpaque(false);

        lblUpdate.setFont(new java.awt.Font("Impact", 0, 32)); // NOI18N
        lblUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setText("Update");
        lblUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
        });

        lblEdit.setFont(new java.awt.Font("Impact", 0, 32)); // NOI18N
        lblEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEdit.setText("Edit");
        lblEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
        });

        lblNew.setFont(new java.awt.Font("Impact", 0, 32)); // NOI18N
        lblNew.setForeground(new java.awt.Color(255, 255, 255));
        lblNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNew.setText("Submit");
        lblNew.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNew, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNew, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        agnetPanel.setBackground(new java.awt.Color(102, 102, 102));
        agnetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Agent Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        agnetPanel.setOpaque(false);

        lblAname.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblAname.setForeground(new java.awt.Color(255, 255, 255));
        lblAname.setText("Name :");

        lblAid.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblAid.setForeground(new java.awt.Color(255, 255, 255));
        lblAid.setText("Agent ID :");

        lblPosition.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(255, 255, 255));
        lblPosition.setText("Position : ");

        lblAemail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblAemail.setForeground(new java.awt.Color(255, 255, 255));
        lblAemail.setText("Email :");

        lblAtel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblAtel.setForeground(new java.awt.Color(255, 255, 255));
        lblAtel.setText("Mobile No. :");

        txtPosition.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtPosition.setForeground(new java.awt.Color(255, 255, 255));
        txtPosition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtPosition.setOpaque(false);

        txtAgentEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtAgentEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtAgentEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtAgentEmail.setOpaque(false);

        txtAgentName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtAgentName.setForeground(new java.awt.Color(255, 255, 255));
        txtAgentName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtAgentName.setOpaque(false);

        txtAgentID.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtAgentID.setForeground(new java.awt.Color(255, 255, 255));
        txtAgentID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtAgentID.setOpaque(false);

        txtAgentMob.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtAgentMob.setForeground(new java.awt.Color(255, 255, 255));
        txtAgentMob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtAgentMob.setOpaque(false);

        lblPosition1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblPosition1.setForeground(new java.awt.Color(255, 255, 255));
        lblPosition1.setText("Password :");

        txtPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtPassword.setOpaque(false);

        javax.swing.GroupLayout agnetPanelLayout = new javax.swing.GroupLayout(agnetPanel);
        agnetPanel.setLayout(agnetPanelLayout);
        agnetPanelLayout.setHorizontalGroup(
            agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agnetPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agnetPanelLayout.createSequentialGroup()
                        .addComponent(lblPosition1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(agnetPanelLayout.createSequentialGroup()
                        .addGroup(agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(agnetPanelLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agnetPanelLayout.createSequentialGroup()
                                .addGroup(agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAemail, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAgentEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                                    .addComponent(txtAgentName))))
                        .addGroup(agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(agnetPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblAid, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(agnetPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAgentID, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAtel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgentMob, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        agnetPanelLayout.setVerticalGroup(
            agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agnetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAtel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgentMob, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAemail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(agnetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosition1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(opportunityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DescriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agnetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(companyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(companyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agnetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescriptionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opportunityPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(mainPanel);
        mainPanel.setBounds(30, 110, 1270, 570);

        lblLogout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("Logout");
        lblLogout.setToolTipText("");
        lblLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogout);
        lblLogout.setBounds(1140, 20, 130, 40);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1350, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewMouseClicked
        addToDatabase(populateCompanyFeilds(true));
    }//GEN-LAST:event_lblNewMouseClicked

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        allowChange(true);
        lblNew.setVisible(false);
        lblUpdate.setVisible(true);
    }//GEN-LAST:event_lblEditMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        this.dispose();
        li.setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked
        Company c = populateCompanyFeilds(false);
        boolean successfulAddition;
        DBOperations db = new DBOperations();
        System.out.println("update data student interface 1");
        successfulAddition = db.updateCompany(c);
        if (successfulAddition) {
            JOptionPane.showMessageDialog(this, "Added Successfully");
            allowChange(false);                                                    //disabling the editing feature of text boxes
        } else {
            JOptionPane.showMessageDialog(this, "Error occured while inserting !!! ");
        }
    }//GEN-LAST:event_lblUpdateMouseClicked

    private void lblVIewApplicationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVIewApplicationsMouseClicked
        try {
            String opID = txtOpID.getText();
            ResultSet rs = db.getSelectedStudents(opID);
            while (rs.next()) {
                System.out.println(rs.getString(1));
                String[] rr = convertArray(db.getContact(rs.getString(1), "student_details"));

                applicantList.add(rr);
            }

            String[][] ss = new String[applicantList.size()][];
            applicantList.toArray(ss);
            ApplicationsTableForCompany ac = new ApplicationsTableForCompany(ss);
            tblApplications.setModel(ac);
        } catch (SQLException ex) {
            Logger.getLogger(CompanyInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        tab2.setVisible(true);
        mainPanel.setVisible(false);
    }//GEN-LAST:event_lblVIewApplicationsMouseClicked

    private void lblVIewApplications1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVIewApplications1MouseClicked
        mainPanel.setVisible(true);
        tab2.setVisible(false);
    }//GEN-LAST:event_lblVIewApplications1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyInterface(li,true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel DescriptionPanel;
    private javax.swing.JPanel agnetPanel;
    private javax.swing.JPanel companyPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAemail;
    private javax.swing.JLabel lblAid;
    private javax.swing.JLabel lblAname;
    private javax.swing.JLabel lblAtel;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblComTel;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblOpID;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblPosition1;
    private javax.swing.JLabel lblSkills;
    private javax.swing.JLabel lblSlots;
    private javax.swing.JLabel lblTiltle;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblVIewApplications;
    private javax.swing.JLabel lblVIewApplications1;
    private javax.swing.JLabel lblemail;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel opportunityPanel;
    private javax.swing.JPanel tab2;
    private javax.swing.JTable tblApplications;
    private javax.swing.JTextField txtAgentEmail;
    private javax.swing.JTextField txtAgentID;
    private javax.swing.JTextField txtAgentMob;
    private javax.swing.JTextField txtAgentName;
    private javax.swing.JTextField txtComAddress;
    private javax.swing.JTextField txtComEmail;
    private javax.swing.JTextField txtComName;
    private javax.swing.JTextField txtComTel;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtOpID;
    private javax.swing.JTextField txtOpTitle;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextArea txtSkills;
    private javax.swing.JTextField txtSlots;
    // End of variables declaration//GEN-END:variables

//--------------------------------------------------------------------------------------------------------------------------------------------
    Company populateCompanyFeilds(boolean newUser){        // method to populate the variables inside the company class
        Company c = new Company();
        if (!newUser)
            c.setCompanyID(Integer.parseInt(txtOpID.getText()));
        c.setAgentName(txtAgentName.getText());
        c.setAgentID(txtAgentID.getText());
        c.setPassword(txtPassword.getText());
        c.setCompanyName(txtComName.getText());
        c.setPosition(txtPosition.getText());
        c.setAgentEmail(txtAgentEmail.getText());
        c.setMobile(txtAgentMob.getText());
        c.setLandline(txtComTel.getText());
        c.setAddress(txtComAddress.getText());
        c.setSlots(Integer.parseInt(txtSlots.getText()));
        c.setSkills(txtSkills.getText());
        c.setOppName(txtOpTitle.getText());
        c.setDescription(txtDescription.getText());
        c.setComEmail(txtComEmail.getText());
        System.out.println("opid text "+txtOpID.getText());
        System.out.println("company login -  populateCompanyFields");
        System.out.println("populate - "+c.getCompanyID());
        return c;
    }
//--------------------------------------------------------------------------------------------------------------------------------------------
void addToDatabase(Company c){
boolean successfulAddition;
     DBOperations db = new DBOperations();
     successfulAddition = db.addCompany(c);
     if (successfulAddition){
         JOptionPane.showMessageDialog(this, "Added Successfully");
         allowChange(false);                                                    //disabling the editing feature of text boxes
         JOptionPane.showMessageDialog(this, "You will be directed back to the home page !");
         this.dispose();
         li.setVisible(true);
     }
     else
         JOptionPane.showMessageDialog(this, "Error occured while inserting !!! ");
}
//--------------------------------------------------------------------------------------------------------------------------------------------    
void allowChange(boolean change) {
        txtComName.setEditable(change);
        txtComTel.setEditable(change);
        txtComEmail.setEditable(change);
        txtComAddress.setEditable(change);
        txtAgentName.setEditable(change);
        txtAgentID.setEditable(change);
        txtAgentMob.setEditable(change);
        txtAgentEmail.setEditable(change);
        txtPosition.setEditable(change);
        txtPassword.setEditable(change);
        txtOpTitle.setEditable(change);
        txtOpID.setEditable(false);                                             //this is automatically filled by the server
        txtSlots.setEditable(change);
        txtSkills.setEditable(change);
        txtDescription.setEditable(change);
        if (change) {
            lblNew.setVisible(change);
            lblEdit.setVisible(false);
            lblUpdate.setVisible(false);
        } else {
           lblNew.setVisible(false);
           lblEdit.setVisible(true);
           lblUpdate.setVisible(false);
        }
    }
//-------------------------------------------------------------------------------------------------------------------------------------------
void fillInfo(Company c){                                                     // fill the details in the GUI for a given student 
    txtComName.setText(c.getCompanyName());
    txtComTel.setText(c.getLandline());
    txtComEmail.setText(c.getComEmail());
    txtComAddress.setText(c.getAddress());
    txtAgentName.setText(c.getAgentName());
    txtAgentID.setText(c.getAgentID());
    txtAgentMob.setText(c.getMobile());
    txtAgentEmail.setText(c.getAgentEmail());
    txtPosition.setText(c.getPosition());
    txtPassword.setText(c.getPassword());
    txtOpTitle.setText(c.getOppName());
    txtOpID.setText(Integer.toString(c.getCompanyID()));
    txtSlots.setText(Integer.toString(c.getSlots()));
    txtSkills.setText(c.getSkills());
    txtDescription.setText(c.getDescription());
}
//-------------------------------------------------------------------------------------------------------------------------------------------

    public String[] convertArray(ResultSet rs) {
        try {
            System.out.println("studentinternshipapplication.CompanyInterface.convertArray()");
            String[] s = new String[10];
            rs.next();
            s[0] = (rs.getString(1));
            s[1] = (rs.getString(3));
            s[2] = (rs.getString(8));
            s[3] = (rs.getString(10));
            s[4] = (rs.getString(11));
            s[5] = (rs.getString(13));
            s[6] = (rs.getString(4));
            s[7] = (rs.getString(5));
            s[8] = (rs.getString(6));
            s[9] = (rs.getString(12));

            
            return s;
        } catch (Exception e) {
            System.out.println("methanin penne yako");
            System.out.println(e);
            return null;

        }
    }

}
