/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinternshipapplication;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class StudentInterface extends javax.swing.JFrame {

    static LoginInterface li ;          //to handle windows
    StudentInterface si;                //to handle windows
    String[][] oppList;                     //this list contain the details about apportunity
    ArrayList<String[]> selectedOpList = new ArrayList<>();
    SelectedOPTable sTable; 
    TableOpportunityList comTable;
    ArrayList<String[]> interviewList= new ArrayList<>();
    
   Company c = new Company();
   DBOperations db = new DBOperations();
   static boolean editable = false;          //user able to edit the content - false means user is already in the system 

//----------------------------------------------------------------------------------------------------------------------------------------------    
    public StudentInterface(LoginInterface l ,boolean edit) {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x_size = 1350;
        int y_size=720;
        this.setSize(x_size,y_size);
        StudentInterface.li = l;                                //getting the address of LoginWindow 
        allowChange(edit);
        tab2.setVisible(false);
        lblOPLsit.setVisible(false);
        tablePanel.setVisible(false);
      
     
    }
//----------------------------------------------------------------------------------------------------------------------------------------------
    void setStudentInterface(StudentInterface li){          //to store the address of the current object
        this.si = li;
    }
//----------------------------------------------------------------------------------------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInterview = new javax.swing.JLabel();
        lblOPLsit = new javax.swing.JLabel();
        lblMyProfile = new javax.swing.JLabel();
        tab1 = new javax.swing.JPanel();
        generalInforPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtxID = new javax.swing.JTextField();
        comboDepartment = new javax.swing.JComboBox<>();
        contactDetailsPanel = new javax.swing.JPanel();
        lblMob = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        otherDetailsPanel = new javax.swing.JPanel();
        lblBirthday = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        comboGender = new javax.swing.JComboBox<>();
        txtxNIC = new javax.swing.JTextField();
        skillsPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSkills = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblbGPA = new javax.swing.JLabel();
        txtGPA = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLanguages = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        lblSubmitData = new javax.swing.JLabel();
        lblEditData = new javax.swing.JLabel();
        lblUpdateData = new javax.swing.JLabel();
        lblEditData2 = new javax.swing.JLabel();
        lblApproval = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOppList = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnRemoveOpp = new javax.swing.JButton();
        btnAddOpportunity = new javax.swing.JButton();
        btnupdateOppTable = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSelectedOp = new javax.swing.JTable();
        tablePanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblinterview = new javax.swing.JTable();
        lblLogout = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        lblEditData1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        lblInterview.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblInterview.setForeground(new java.awt.Color(255, 255, 255));
        lblInterview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInterview.setText("Interviews");
        lblInterview.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblInterview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInterview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInterviewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInterviewMouseEntered(evt);
            }
        });
        getContentPane().add(lblInterview);
        lblInterview.setBounds(470, 30, 160, 40);

        lblOPLsit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOPLsit.setForeground(new java.awt.Color(255, 255, 255));
        lblOPLsit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOPLsit.setText("Opportunity List");
        lblOPLsit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblOPLsit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOPLsit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOPLsitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOPLsitMouseEntered(evt);
            }
        });
        getContentPane().add(lblOPLsit);
        lblOPLsit.setBounds(250, 25, 160, 40);

        lblMyProfile.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMyProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblMyProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMyProfile.setText("My Profile");
        lblMyProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblMyProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMyProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMyProfileMouseClicked(evt);
            }
        });
        getContentPane().add(lblMyProfile);
        lblMyProfile.setBounds(30, 25, 160, 40);

        tab1.setOpaque(false);

        generalInforPanel.setBackground(new java.awt.Color(102, 102, 102));
        generalInforPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gereral Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        generalInforPanel.setForeground(new java.awt.Color(255, 255, 255));
        generalInforPanel.setOpaque(false);

        lblName.setBackground(new java.awt.Color(153, 153, 153));
        lblName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name : ");

        lblId.setBackground(new java.awt.Color(153, 153, 153));
        lblId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("ID Number :");

        lblDepartment.setBackground(new java.awt.Color(153, 153, 153));
        lblDepartment.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartment.setText("Department :");

        txtName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtName.setOpaque(false);

        txtxID.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtxID.setForeground(new java.awt.Color(255, 255, 255));
        txtxID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtxID.setOpaque(false);

        comboDepartment.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comboDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronic and Telecommunication Enginnering", "Biomedical Engineering", "Computer Science and Engineering", "Electrical Engineering", "Civil Engineering", "Mechanical Engineering", "Chemical Engineering\t", "Material Engineering" }));

        javax.swing.GroupLayout generalInforPanelLayout = new javax.swing.GroupLayout(generalInforPanel);
        generalInforPanel.setLayout(generalInforPanelLayout);
        generalInforPanelLayout.setHorizontalGroup(
            generalInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalInforPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(generalInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(generalInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName)
                    .addComponent(txtxID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        generalInforPanelLayout.setVerticalGroup(
            generalInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalInforPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(generalInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(generalInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtxID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(generalInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contactDetailsPanel.setBackground(new java.awt.Color(102, 102, 102));
        contactDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        contactDetailsPanel.setOpaque(false);

        lblMob.setBackground(new java.awt.Color(153, 153, 153));
        lblMob.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMob.setForeground(new java.awt.Color(255, 255, 255));
        lblMob.setText("Mobile Number :");

        lblEmail.setBackground(new java.awt.Color(153, 153, 153));
        lblEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email :");

        lblAddress.setBackground(new java.awt.Color(153, 153, 153));
        lblAddress.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Contact Address:");

        txtMobileNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtMobileNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtMobileNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtMobileNumber.setOpaque(false);

        txtEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEmail.setOpaque(false);

        txtAddress.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtAddress.setOpaque(false);

        javax.swing.GroupLayout contactDetailsPanelLayout = new javax.swing.GroupLayout(contactDetailsPanel);
        contactDetailsPanel.setLayout(contactDetailsPanelLayout);
        contactDetailsPanelLayout.setHorizontalGroup(
            contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMob, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        contactDetailsPanelLayout.setVerticalGroup(
            contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contactDetailsPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMob, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        otherDetailsPanel.setBackground(new java.awt.Color(102, 102, 102));
        otherDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        otherDetailsPanel.setOpaque(false);

        lblBirthday.setBackground(new java.awt.Color(153, 153, 153));
        lblBirthday.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBirthday.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthday.setText("Date of Birth : ");

        lblGender.setBackground(new java.awt.Color(153, 153, 153));
        lblGender.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender:");

        lblNIC.setBackground(new java.awt.Color(153, 153, 153));
        lblNIC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNIC.setForeground(new java.awt.Color(255, 255, 255));
        lblNIC.setText("NIC number:");

        txtBirthday.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtBirthday.setForeground(new java.awt.Color(255, 255, 255));
        txtBirthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtBirthday.setOpaque(false);

        comboGender.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        txtxNIC.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtxNIC.setForeground(new java.awt.Color(255, 255, 255));
        txtxNIC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtxNIC.setOpaque(false);

        javax.swing.GroupLayout otherDetailsPanelLayout = new javax.swing.GroupLayout(otherDetailsPanel);
        otherDetailsPanel.setLayout(otherDetailsPanelLayout);
        otherDetailsPanelLayout.setHorizontalGroup(
            otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNIC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBirthday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherDetailsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(otherDetailsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtxNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        otherDetailsPanelLayout.setVerticalGroup(
            otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtxNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        skillsPanel.setBackground(new java.awt.Color(102, 102, 102));
        skillsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Skills", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        skillsPanel.setOpaque(false);

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Skills:");

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CV : ");

        txtSkills.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtSkills.setForeground(new java.awt.Color(255, 255, 255));
        txtSkills.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtSkills.setOpaque(false);

        txtPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtPassword.setOpaque(false);

        jLabel14.setBackground(new java.awt.Color(153, 153, 153));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Password :");

        lblbGPA.setBackground(new java.awt.Color(153, 153, 153));
        lblbGPA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblbGPA.setForeground(new java.awt.Color(255, 255, 255));
        lblbGPA.setText("Final GPA:");

        txtGPA.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtGPA.setForeground(new java.awt.Color(255, 255, 255));
        txtGPA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtGPA.setOpaque(false);

        jLabel13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Languages:");

        txtLanguages.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtLanguages.setForeground(new java.awt.Color(255, 255, 255));
        txtLanguages.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtLanguages.setOpaque(false);

        javax.swing.GroupLayout skillsPanelLayout = new javax.swing.GroupLayout(skillsPanel);
        skillsPanel.setLayout(skillsPanelLayout);
        skillsPanelLayout.setHorizontalGroup(
            skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(skillsPanelLayout.createSequentialGroup()
                        .addComponent(txtLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(skillsPanelLayout.createSequentialGroup()
                        .addComponent(txtSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblbGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        skillsPanelLayout.setVerticalGroup(
            skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, skillsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(0, 0, 0));
        txtDescription.setRows(5);
        txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtDescription.setOpaque(false);
        jScrollPane1.setViewportView(txtDescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );

        buttonPanel.setBackground(new java.awt.Color(0, 153, 153));
        buttonPanel.setOpaque(false);

        lblSubmitData.setFont(new java.awt.Font("Impact", 0, 32)); // NOI18N
        lblSubmitData.setForeground(new java.awt.Color(255, 255, 255));
        lblSubmitData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubmitData.setText("Submit Data");
        lblSubmitData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblSubmitData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSubmitData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSubmitData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSubmitDataMouseClicked(evt);
            }
        });

        lblEditData.setFont(new java.awt.Font("Impact", 0, 32)); // NOI18N
        lblEditData.setForeground(new java.awt.Color(255, 255, 255));
        lblEditData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditData.setText("Edit Data");
        lblEditData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblEditData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEditData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditDataMouseClicked(evt);
            }
        });

        lblUpdateData.setFont(new java.awt.Font("Impact", 0, 32)); // NOI18N
        lblUpdateData.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateData.setText("Update Data");
        lblUpdateData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblUpdateData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUpdateData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUpdateData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateDataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubmitData, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateData, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditData, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addComponent(lblEditData, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUpdateData, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSubmitData, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblEditData2.setFont(new java.awt.Font("Impact", 0, 32)); // NOI18N
        lblEditData2.setForeground(new java.awt.Color(255, 255, 255));
        lblEditData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditData2.setText("Upload CV");
        lblEditData2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblEditData2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditData2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEditData2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditData2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addComponent(generalInforPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contactDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addComponent(otherDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(skillsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233)
                        .addComponent(lblEditData2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generalInforPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(skillsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(otherDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                        .addComponent(lblEditData2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        getContentPane().add(tab1);
        tab1.setBounds(10, 80, 1330, 600);

        lblApproval.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblApproval.setForeground(new java.awt.Color(255, 51, 51));
        lblApproval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApproval.setText("Approval Pending");
        lblApproval.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(lblApproval);
        lblApproval.setBounds(910, 20, 230, 60);

        tab2.setOpaque(false);

        tblOppList.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tblOppList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Opportunity ID", "Opprotunity Titile ", "Company Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOppList.setInheritsPopupMenu(true);
        tblOppList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOppListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblOppList);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setOpaque(false);

        btnRemoveOpp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRemoveOpp.setText("Add");
        btnRemoveOpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOppActionPerformed(evt);
            }
        });

        btnAddOpportunity.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAddOpportunity.setText("Remove");
        btnAddOpportunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOpportunityActionPerformed(evt);
            }
        });

        btnupdateOppTable.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnupdateOppTable.setText("Submit");
        btnupdateOppTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateOppTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnRemoveOpp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnAddOpportunity, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnupdateOppTable, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOpportunity)
                    .addComponent(btnRemoveOpp)
                    .addComponent(btnupdateOppTable))
                .addGap(5, 5, 5))
        );

        tblSelectedOp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tblSelectedOp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Preference Order", "Opportunity ID", "Opportunity Title", "Company Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblSelectedOp);

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)))
                .addContainerGap(692, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(tab2);
        tab2.setBounds(10, 80, 1330, 600);

        tablePanel.setOpaque(false);

        tblinterview.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tblinterview.setForeground(new java.awt.Color(0, 0, 0));
        tblinterview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblinterview);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1306, Short.MAX_VALUE)
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(tablePanel);
        tablePanel.setBounds(10, 80, 1330, 600);

        lblLogout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("Logout");
        lblLogout.setToolTipText("");
        lblLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogout);
        lblLogout.setBounds(1154, 20, 160, 40);

        background.setBackground(new java.awt.Color(255, 51, 51));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7EzRMg5.jpg"))); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background);
        background.setBounds(0, 0, 1350, 700);

        lblEditData1.setFont(new java.awt.Font("Impact", 0, 32)); // NOI18N
        lblEditData1.setForeground(new java.awt.Color(255, 255, 255));
        lblEditData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditData1.setText("Edit Data");
        lblEditData1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblEditData1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditData1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEditData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditData1MouseClicked(evt);
            }
        });
        getContentPane().add(lblEditData1);
        lblEditData1.setBounds(0, 0, 120, 46);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSubmitDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubmitDataMouseClicked
        addToDatabase(populateStudentFields());
    }//GEN-LAST:event_lblSubmitDataMouseClicked

    private void lblEditDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditDataMouseClicked
        txtName.setEditable(true);                                        //since if the user is already in the system, user dont need to change
        txtxID.setEditable(false);                                           //bio data over each login
        txtAddress.setEditable(true);
        txtBirthday.setEditable(true);
        txtDescription.setEditable(true);
        txtGPA.setEditable(true);
        txtEmail.setEditable(true);
        txtLanguages.setEditable(true);
        txtxNIC.setEditable(true);
        txtSkills.setEditable(true);
        txtMobileNumber.setEditable(true);
        lblEditData.setVisible(false);
        lblUpdateData.setVisible(true);
    }//GEN-LAST:event_lblEditDataMouseClicked

    private void lblUpdateDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateDataMouseClicked
        Student s = populateStudentFields();
        boolean successfulAddition;
        DBOperations db = new DBOperations();
        System.out.println("update data student interface 1");
        successfulAddition = db.updateStudent(s);
        if (successfulAddition) {
            JOptionPane.showMessageDialog(this, "Added Successfully");
            allowChange(false);                                                    //disabling the editing feature of text boxes
        } else {
            JOptionPane.showMessageDialog(this, "Error occured while inserting !!! ");
        }
    }//GEN-LAST:event_lblUpdateDataMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        this.dispose();
        li.setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblEditData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditData1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEditData1MouseClicked

    private void lblOPLsitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOPLsitMouseClicked
        tab1.setVisible(false);
        tab2.setVisible(true);
        tablePanel.setVisible(false);
        loadOpportunity();
        loadSelectedOpportunity();
    }//GEN-LAST:event_lblOPLsitMouseClicked

    private void lblMyProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyProfileMouseClicked
        tablePanel.setVisible(false);
        tab1.setVisible(true);
        tab2.setVisible(false);
    }//GEN-LAST:event_lblMyProfileMouseClicked

    private void btnRemoveOppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOppActionPerformed
        System.gc();
        System.out.println("studentinternshipapplication.StudentInterface.btnAddOppActionPerformed()");
        String[] temp = new String[4];
        temp[0] = Integer.toString(selectedOpList.size()+1);
        int row = tblOppList.getSelectedRow();
        temp[1] =  (String)tblOppList.getValueAt(row,0 );
        temp[2] =  (String)tblOppList.getValueAt(row,1 );
        temp[3] =  (String)tblOppList.getValueAt(row,2 );
        selectedOpList.add(temp);
        sTable = new SelectedOPTable(selectedOpList);
        tblSelectedOp.setModel(sTable);
    }//GEN-LAST:event_btnRemoveOppActionPerformed

    private void btnAddOpportunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOpportunityActionPerformed
        if (tblOppList.getSelectedRow() != -1) {
            System.gc();
            System.out.println("studentinternshipapplication.StudentInterface.btnRemoveOpActionPerformed()");
            int row = tblSelectedOp.getSelectedRow();
            selectedOpList.remove(row);
            System.out.println("array index" + selectedOpList.size());
            sTable = new SelectedOPTable(selectedOpList);
            tblSelectedOp.setModel(sTable);
        }
    }//GEN-LAST:event_btnAddOpportunityActionPerformed

    private void btnupdateOppTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateOppTableActionPerformed
        if (tblOppList.getSelectedRow() != -1) {
            String stID = txtxID.getText();
            String[][] ss = new String[selectedOpList.size()][];
            selectedOpList.toArray(ss);
            for (int i = 0; i < selectedOpList.size(); i++) {
                db.addSelectOpportunities(stID, Integer.parseInt(ss[i][1]), i + 1);
            }
        }
    }//GEN-LAST:event_btnupdateOppTableActionPerformed

    private void tblOppListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOppListMouseClicked
        
    }//GEN-LAST:event_tblOppListMouseClicked

    private void lblOPLsitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOPLsitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOPLsitMouseEntered

    private void lblInterviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInterviewMouseClicked
       tab1.setVisible(false);
       tablePanel.setVisible(true);
       tab2.setVisible(false);
       String opID = txtxID.getText();
       String[] rs = db.getSelectedCompanies(opID);
       System.out.println(opID);
       for(int i=0;i<3;i++){
           System.out.println(rs[i]);
           if (rs[i]!=null){
               String[] rr = convertArray(db.getCompanyInfo(rs[i]));
               interviewList.add(rr);
           }
       }
       String[][] ss = new String[interviewList.size()][];
       interviewList.toArray(ss);
       TableModelForSelecctedOpForStudents ac = new TableModelForSelecctedOpForStudents(ss);
       tblinterview.setModel(ac); 
        
    }//GEN-LAST:event_lblInterviewMouseClicked

    private void lblInterviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInterviewMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInterviewMouseEntered

    private void lblEditData2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditData2MouseClicked
        DataBaseTrail DT = new DataBaseTrail();
        try{
            DT.writeToDB(txtxID.getText());
        }catch(Exception e){
            System.out.println("Exception***********************************************");
            System.out.println("studentinternshipapplication.StudentInterface.jButton1ActionPerformed()");
        }
    }//GEN-LAST:event_lblEditData2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInterface(li,editable).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAddOpportunity;
    private javax.swing.JButton btnRemoveOpp;
    private javax.swing.JButton btnupdateOppTable;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> comboDepartment;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JPanel contactDetailsPanel;
    private javax.swing.JPanel generalInforPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblApproval;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEditData;
    private javax.swing.JLabel lblEditData1;
    private javax.swing.JLabel lblEditData2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInterview;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMob;
    private javax.swing.JLabel lblMyProfile;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOPLsit;
    private javax.swing.JLabel lblSubmitData;
    private javax.swing.JLabel lblUpdateData;
    private javax.swing.JLabel lblbGPA;
    private javax.swing.JPanel otherDetailsPanel;
    private javax.swing.JPanel skillsPanel;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTable tblOppList;
    private javax.swing.JTable tblSelectedOp;
    private javax.swing.JTable tblinterview;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtLanguages;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSkills;
    private javax.swing.JTextField txtxID;
    private javax.swing.JTextField txtxNIC;
    // End of variables declaration//GEN-END:variables

//------------------------------------------------------------------------------------------------------------------------------------------
public void allowChange(boolean edit){                              //this methods controls the editable rights of the fields
            txtName.setEditable(edit);                                        //since if the user is already in the system, user dont need to change
            txtxID.setEditable(edit);                                           //bio data over each login
            txtAddress.setEditable(edit);
            txtBirthday.setEditable(edit);
            txtDescription.setEditable(edit);
            txtGPA.setEditable(edit);
            txtEmail.setEditable(edit);
            txtLanguages.setEditable(edit);
            txtxNIC.setEditable(edit);
            txtSkills.setEditable(edit);
            txtMobileNumber.setEditable(edit);
            txtPassword.setEditable(edit);
            if (edit == false){
                lblSubmitData.setVisible(edit);                               //setting the submit button visible to new users
                lblEditData.setVisible(true);
                lblUpdateData.setVisible(false);
            }else{
                lblEditData.setVisible(false);
                lblUpdateData.setVisible(false);
            }
    }
//------------------------------------------------------------------------------------------------------------------------------------------
Student populateStudentFields() {                                   //method to populate Student fields 
        Student s = new Student();
        s.setName(txtName.getText());
        s.setID(txtxID.getText());
        s.setDepartnment(String.valueOf(comboDepartment.getSelectedItem()));
        s.setTelephone(txtMobileNumber.getText());
        s.setEmail(txtEmail.getText());
        s.setAddress(txtAddress.getText());
        s.setBirthday(txtBirthday.getText());
        s.setGender(String.valueOf(comboGender.getSelectedItem()));
        s.setNIC(txtxNIC.getText());
        s.setGPA(Float.parseFloat(txtGPA.getText()));
        s.setLanguages(txtLanguages.getText());
        s.setDescription(txtDescription.getText());
        s.setSkills(txtSkills.getText());
        s.setPassword(txtPassword.getText());
        if ("Approval Pending".equals(lblApproval.getText())) {
            s.setAdminAccepted("Pending");
        }
    return s;
    }
//----------------------------------------------------------------------------------------------------------------------------------------
void addToDatabase(Student s){                                      //to add the data to database 
    boolean successfulAddition;
     DBOperations db = new DBOperations();
     successfulAddition = db.addStudent(s);
     if (successfulAddition){
         JOptionPane.showMessageDialog(this, "Added Successfully");
         allowChange(false);                                                    //disabling the editing feature of text boxes
         JOptionPane.showMessageDialog(this, "You will be directed back to the home page !");
         this.dispose();
         li.setVisible(true);
     }
     else
         JOptionPane.showMessageDialog(this, "Error occured while inserting !!! ");
}
//-----------------------------------------------------------------------------------------------------------------------------------------
void fillInfo(Student s) {                                                     // fill the details in the GUI for a given student 
        txtAddress.setText(s.getAddress());
        txtBirthday.setText(s.getBirthday());
        txtDescription.setText(s.getDescription());
        txtEmail.setText(s.getEmail());
        txtGPA.setText(Float.toString(s.getGPA()));
        txtLanguages.setText(s.getLanguages());
        txtMobileNumber.setText(s.getTelephone());
        txtName.setText(s.getName());
        txtPassword.setText(s.getPassword());
        txtSkills.setText(s.getSkills());
        txtxID.setText(s.getID());
        txtxNIC.setText(s.getNIC());
        comboDepartment.setSelectedItem(s.getDepartnment());
        comboGender.setSelectedItem(s.getGender());
        if ("Pending".equals(s.getAdminAccepted())) {
            lblApproval.setText("Approval Pending");
            lblApproval.setForeground(new Color(255, 255, 5));
            lblOPLsit.setVisible(false);
        } else if ("Accepted".equals(s.getAdminAccepted())) {
            lblApproval.setText("Admin Accepted");
            lblApproval.setForeground(new Color(0, 204, 153));
            lblOPLsit.setVisible(true);
        } else {
            lblApproval.setText("Rejected");
            lblApproval.setForeground(new Color(255, 0, 102));
            lblOPLsit.setVisible(false);
        }
    }
//--------------------------------------------------------------------------------------------------------------------------------------

    void loadOpportunity() {
        System.out.println("loadCompany method in adminInterface class");
        oppList = c.setMiniDataForStudentTable(db.retrieveOpptunityListForStudent());
        comTable = new TableOpportunityList(oppList);
        tblOppList.setModel(comTable);
    }
//--------------------------------------------------------------------------------------------------------------------------------------

    void loadSelectedOpportunity() {
        System.out.println("loadSelectedOpportunity method in adminInterface class");
        sTable = new SelectedOPTable(selectedOpList);
        tblSelectedOp.setModel(sTable);
    }
//--------------------------------------------------------------------------------------------------------------------------------------    
public String[] convertArray(ResultSet rs) {
        try {
            System.out.println("studentinternshipapplication.CompanyInterface.convertArray()");
            String[] s = new String[5];
            rs.next();
            s[0] = (rs.getString(5));
            s[1] = (rs.getString(13));
            s[2] = (rs.getString(15));
            s[3] = (rs.getString(12));
            s[4] = (rs.getString(14));
            System.out.println( s[0]+s[1]+s[2]+s[3]+s[4]);

            return s;
        } catch (Exception e) {
            System.out.println("methanin penne yako");
            System.out.println(e);
            return null;

        }
    }
}
